### ISSUE TITLE
Novo erro ao fazer Deploys

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/storefront-ci#37]
Ao fazer o post para deploy no storefrontci está retornando um erro 500, após retentativas o erro persiste. 
É criado o repositório no github e o site no ntlify, mas não é possível efetuar o login no cms. 

Segue o body do erro:

```
{
    "message": "connect EHOSTUNREACH 172.64.81.144:443",
    "name": "Error",
    "stack": "Error: connect EHOSTUNREACH 172.64.81.144:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
    "config": {
        "url": "/admin/users",
        "method": "get",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTY1MTc3NDUsInN1YiI6IjZiNDA5MDFiLTBlMmUtNGViYS04MDc3LTQwZWVmMTU0YTY5MiIsImVtYWlsIjoic2Vydmlkb3JAZS1jb20uY2x1YiIsImFwcF9tZXRhZGF0YSI6e30sInVzZXJfbWV0YWRhdGEiOnt9fQ.uOZ5jPI3Tl-CFCcdvY5szvqKh10OBUp7ObWZdro77SU",
            "User-Agent": "axios/0.21.1"
        },
        "baseURL": "https://gotrue.ecomplus.biz",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 1000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1
    },
    "code": "EHOSTUNREACH"
}
```

**Comment by vitorrgg** [comment]
Tentei fazer um outro deploy de outra loja recem criada, e mesmo com o ID correto apareceu o erro 500 antes relatado. Segue o body do mesmo. 

{
    "message": "connect EHOSTUNREACH 172.64.81.155:443",
    "name": "Error",
    "stack": "Error: connect EHOSTUNREACH 172.64.81.155:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
    "config": {
        "url": "/admin/users",
        "method": "post",
        "data": "{\"store_id\":\"1237\",\"name\":\"cpepper\",\"email\":\"tiago.sl.basto@gmail.com\",\"password\":\"J!wm2mdE\",\"confirm\":true}",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8",
            "Authorization": "-",
            "User-Agent": "axios/0.21.1",
            "Content-Length": 108
        },
        "baseURL": "https://gotrue.ecomplus.biz",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 1000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1
    },
    "code": "EHOSTUNREACH"
}
