### ISSUE TITLE
Promise do git gateway sem catch (?)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#5]
```console
(node:11086) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'msg' of undefined
    at createInstance.then.catch.error (/src/api/GitGateway.js:21:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by thiagoabreudev** [comment]
https://github.com/thiagoabreudev/storefront-ci/pull/5/
